### ISSUE TITLE
DQN用シミュレータを作成する

### ISSUE THREAD

**Issue by sinmetal** [sinmetal/metal-tile#30]
機械学習するためにシミュレータを作成する
## ありそうな機能
- map の状態をランダムに生成
- プレイヤーを適当に配置する (プレイヤーはランダムに動く？)
#8

**Comment by sfujiwara** [comment]
シミュレータで実際にプレイさせてデータを作りながら学習していくことになるので、シミュレータも Python で作っておいた方が良いっぽいです。

とりあえずリポジトリ作っておきました。
TensorFlow を使った学習用クラスは作成済みなので、あとはシミュレータを実装して学習させれば OK という段階です。
https://github.com/sfujiwara/dqn-tensorflow

**Comment by sinmetal** [comment]
@sfujiwara 👍
