### ISSUE TITLE
DQNが合体する

### ISSUE THREAD

**Issue by sfujiwara** [sinmetal/metal-tile#35]
ゲーム側からDQNを呼び出せるようにうまいこと繋ぐ

**Comment by sinmetal** [comment]
```
{"predictions": [{"q": [0.4523559808731079, 0.38499385118484497, 0.26314204931259155, 0.6228029131889343, 0.5784728527069092], "key": 0}]}
```

* 何もしない
* 右
* 左
* 上
* 下

**Comment by sfujiwara** [comment]
[3 x 84 x 84] の配列を送る感じにしましょう。
フィールドの情報を 84 x 84 の配列で表して、それを3つ送る感じです。
3つの役割はそれぞれ

* 追いかける奴の場所が1で他が0になっている[84 x 84]の配列
* 追いかけられる奴の場所が1で他が0になっている[84 x 84]の配列
* 障害物がある場所が1で他が0になっている[84 x 84]の配列
