### ISSUE TITLE
敵モンスターのAIを作成する

### ISSUE THREAD

**Issue by sinmetal** [sinmetal/metal-tile#8]
キャラクターに向かって近付いていくぐらいを作ってみる

Compute Engine上でFirebaseのDBを見ながら、適当に操作する感じ？
https://github.com/zabawaba99/firego

**Comment by sfujiwara** [comment]
@sinmetal [DQN (Deep Q-Network)](https://arxiv.org/abs/1312.5602) の実装を始めました。
とりあえず使いそうなデータはこんな感じです。

* 盤面の状態を2次元配列で
  - 画像とか画面の色でも良いし、壁や人を適当な数値で表しても良い
* その盤面で押したボタンがどれか
* その結果変化した後の盤面の状態を、これも2次元配列で
* その結果何かAIにとって良いことか悪いことが起こったら、それを適当なスコアで
  - 近付くことが目的の場合、キャラクターに接触したら1、それ以外は0とか
  - 距離もスコアとして入れてあげると良いかもしれないけれど、その辺は多分適当で良さそう

実際にプレイさせながら学習させても良いけれど、それだと学習が遅いので、ある程度ちゃんと動くかの確認のためにシミュレータっぽいもの作った方が良いかもしれないです。

**Comment by sinmetal** [comment]
@sfujiwara なるほど。準備できるように実装してみよう。

> その盤面で押したボタンがどれか

というのは、AI側が押したボタンという意味だろうか？

> 実際にプレイさせながら学習させても良いけれど、それだと学習が遅いので、ある程度ちゃんと動くかの確認のためにシミュレータっぽいもの作った方が良いかもしれないです。

こいつも考えておこう。

**Comment by sfujiwara** [comment]
@sinmetal 

> その盤面で押したボタンがどれか
>> というのは、AI側が押したボタンという意味だろうか？

ですね。
「相手が押したボタン」みたいに本来見えてはいけない情報はズルなので使わないです。

あと、書き忘れてましたが盤面データとセットで「この盤面で1ゲーム終了です」みたいなのを表すフラグも欲しいです。

ルールさえ定まれば、シミュレータは僕の方で実装するのが良いかもですね。
